### ISSUE TITLE
Lacking HTTP 2.0 support

### ISSUE THREAD

**Issue by Syoc** [Cisco-Talos/Re2Pcap#1]
The following response content will result in a pcap:

```
HTTP/1.1 200 OK
Server: nginx

Hello World!
```
This will not:
```
HTTP/2.0 200 OK
Server: nginx

Hello World!
```

**Comment by amit-raut** [comment]
Thank you for reporting the issue. I'll look in to it

-Amit

**Comment by amit-raut** [comment]
Thank you for enhancement request. 🙂

Re2Pcap uses Python3 http.server and currently it does not support HTTP/2.0. 

I may use something like [Twisted](https://twistedmatrix.com/trac/) to have HTTP/2.0 for Re2Pcap in future. I'll keep this issue open for now.

This should not be a problem for PCAPs from Re2Pcap for Snort or IDS testing unless your rule specifically is looking `HTTP/2.0`. If you have HTTP/2.0 traffic I would recommend changing it to HTTP/1.1 and generating PCAP to test your Snort rules.

With [6d09e56](https://github.com/Cisco-Talos/Re2Pcap/commit/6d09e567df39314d744e5b4af77adec1900d45eb) the web interface will let you know if the raw request or response are parsable or not. 

Please pull the latest update to enjoy new features of Re2Pcap 😃

Thank you,
Amit R.
Cisco Talos

**Comment by amit-raut** [comment]
There's still no support for HTTP/2.0 implemented in Python3 http.server as per [source](https://github.com/python/cpython/blob/1890dd235f618d60c938f6904d2e1a8a56f99c1c/Lib/http/server.py#L313) and using other server that supports HTTP/2.0 will require major changes. 

Re2Pcap will support HTTP/2.0; if Python3 http.server implements HTTP/2.0.

Closing this issue. 

Thank you,
Amit Raut
