### ISSUE TITLE
Content-Length is added to HTTP Response no matter what

### ISSUE THREAD

**Issue by Syoc** [Cisco-Talos/Re2Pcap#2]
Given the following HTTP Response input to the web interface:
```
HTTP/1.1 200 OK
Server: nginx

Hello World!
```
We get this in the pcap:
```
HTTP/1.1 200 OK
Content-Length: 12
Server: nginx

Hello World!
```

The Content-Length header field should not be added.

**Comment by amit-raut** [comment]
Thank you for reporting the issue. I'll look in to it

-Amit

**Comment by amit-raut** [comment]
Thank you for reporting the issue. 🙂

For the HTTP server response `Content-Length:` response header is required if the server needs to send data to client. If there is no `Content-Length:` response header then the client will not receive anything.

Sorry that the placeholder text was misleading but in [6d09e56](https://github.com/Cisco-Talos/Re2Pcap/commit/6d09e567df39314d744e5b4af77adec1900d45eb) I fixed it to have valid raw HTTP request and response values. 

Please pull latest update to enjoy additional features of Re2Pcap. 😃

Thank you,
Amit R.
Cisco Talos
