### ISSUE TITLE
Empty host field results in an error

### ISSUE THREAD

**Issue by recvfrom** [Cisco-Talos/Re2Pcap#4]
I tried inputting the following, which is based on a hardcoded HTTP request embedded in a malware sample:

```
POST http://103.253.41.45/status.gif?r=1564065990 HTTP/1.1
Accept : text/html, application/xhtml+xml, */*
Accept-Language: en-us
Content-Type: multipart/form-data
Accept-Encoding: gzip, deflate
Host: 
Content-Length: 10101
Connection: Keep-Alive
Cache-Control: no-cache
```

The following error gets displayed, though:
```
ERROR:__main__: Please Add Host Request Header
```

Is it possible to allow the host field to be empty (containing one space next to the 'Host:' portion)?

Thanks!

**Comment by amit-raut** [comment]
Thank you for creating issue @recvfrom! 

The request you entered is not valid raw HTTP request. The host in this case is `103.253.41.45`. I modified and tested the following request. In my test I was able to get the PCAP with everything.

Also please verify that the headers are correct in your input as `Accept : text/html, application/xhtml+xml, */*` is incorrect header the header should follow colon immediately after it like `Accept: text/html, application/xhtml+xml, */*`

Please try the following request. Also it looks like you want to generate PCAP for .gif file in HTTP. If that is the case you can try [file2pcap](https://talosintelligence.com/file2pcap) 

```
POST /status.gif?r=1564065990 HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Accept-Language: en-us
Content-Type: multipart/form-data
Accept-Encoding: gzip, deflate
Host: 103.253.41.45
Content-Length: 10101
Connection: Keep-Alive
Cache-Control: no-cache
```

Thank you,
Amit
Cisco Talos

**Comment by recvfrom** [comment]
@amit-raut I'm definitely not an expert on this, but it seems like HTTP/1.1 allows it based on posts like this one:

https://github.com/akka/akka-http/issues/1530

Assuming it is supported, it'd be great to be able to mimic what the malware is doing as closely as possible when using Re2Pcap to create a pcap for Snort rule testing.

![image](https://user-images.githubusercontent.com/36489577/62419256-ec9b9d80-b649-11e9-8bb0-3f46e1348f6e.png)

**Comment by amit-raut** [comment]
Thank you for specifying your use case 🙂.  Looks like an interesting sample to reverse

This is doable. I'll push update with fix to this and lot more in some time.

Just one more thing. The initial request is still not valid as URL path starts without `/` but starts with `http`

`POST http://103.253.41.45/status.gif?r=1564065990 HTTP/1.1`

I handled this case by inspecting if the URL path starts with `/` or not. If its not starting with `/` then Re2Pcap will add it and resulting PCAP will have 

`POST /http://103.253.41.45/status.gif?r=1564065990 HTTP/1.1`

I tested the following request and was able to get expected result

```
POST http://103.253.41.45/status.gif?r=1564065990 HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Accept-Language: en-us
Content-Type: multipart/form-data
Accept-Encoding: gzip, deflate
Host: 
Content-Length: 10101
Connection: Keep-Alive
Cache-Control: no-cache

post-data
```

I hope this update fixes this. Feel free to reopen this if you face any related issues

Thank you,
Amit
Cisco Talos

**Comment by amit-raut** [comment]
FIxed in [6d09e56
](https://github.com/Cisco-Talos/Re2Pcap/commit/6d09e567df39314d744e5b4af77adec1900d45eb)

Thank you,
Amit 
Cisco Talos

**Comment by recvfrom** [comment]
@amit-raut awesome, thanks!

Regarding the URI, it looks like the format used is the 'absoluteURI' format described here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2

**Comment by amit-raut** [comment]
You're welcome @recvfrom! 😊

~Amit
