### ISSUE TITLE
why this response can't be parsable

### ISSUE THREAD

**Issue by ArseneLupinhb** [Cisco-Talos/Re2Pcap#6]
HTTP/1.1 200 OK
Server: nginx/1.19.1
Content-Type: application/json; charset=utf-8
Content-Length: 63
Connection: keep-alive

{"Success":true,"ErrorCode":0,"Msg":"登陆成功","Data":null}

**Comment by amit-raut** [comment]
Thank you for creating issue with your inputs. The issues 6 and 7 are fixed in [fe8e32af13802a8a87f58e5e75ae1ba523eea1ae](https://github.com/Cisco-Talos/Re2Pcap/commit/fe8e32af13802a8a87f58e5e75ae1ba523eea1ae).

Thank you,
Amit Raut
