### ISSUE TITLE
why this response can't be parsable too

### ISSUE THREAD

**Issue by ArseneLupinhb** [Cisco-Talos/Re2Pcap#7]
![image](https://user-images.githubusercontent.com/25455238/125050760-dc618800-e0d4-11eb-9cfd-be234b3d42e5.png)

**Comment by amit-raut** [comment]
Thank you for creating issue with your inputs. The issues 6 and 7 are fixed in [fe8e32af13802a8a87f58e5e75ae1ba523eea1ae](https://github.com/Cisco-Talos/Re2Pcap/commit/fe8e32af13802a8a87f58e5e75ae1ba523eea1ae).

Thank you,
Amit Raut
